// export const maintenanceData = [
//   {
//     id: 1,
//     appointmentType: "Manager",
//     dateTime: "2025-08-05T10:15:00.000Z",
//     personName: "Brianna Coleman",
//     purpose: "Monthly review meeting",
//     status: "Confirmed",
//     location: "Meeting Room 1",
//   },
//   {
//     id: 2,
//     appointmentType: "Reception",
//     dateTime: "2025-08-05T14:30:00.000Z",
//     personName: "Cody Cotton",
//     purpose: "Check-in documentation",
//     status: "Pending",
//     location: "Reception Desk",
//   },
//   {
//     id: 3,
//     appointmentType: "Visitor",
//     dateTime: "2025-08-06T09:00:00.000Z",
//     personName: "Joey Harrison",
//     purpose: "Facility tour",
//     status: "Escalated",
//     location: "Lobby Entrance",
//   },
//   {
//     id: 4,
//     appointmentType: "Manager",
//     dateTime: "2025-08-06T16:45:00.000Z",
//     personName: "Zoe Little",
//     purpose: "Staff performance review",
//     status: "Confirmed",
//     location: "Manager's Office",
//   },
//   {
//     id: 5,
//     appointmentType: "Reception",
//     dateTime: "2025-08-07T11:20:00.000Z",
//     personName: "Aniya Boyd",
//     purpose: "Package collection",
//     status: "Completed",
//     location: "Reception Desk",
//   },
//   {
//     id: 6,
//     appointmentType: "Visitor",
//     dateTime: "2025-08-07T13:15:00.000Z",
//     personName: "Lilith Thompson",
//     purpose: "Partnership proposal",
//     status: "Pending",
//     location: "Dining Hall",
//   },
//   {
//     id: 7,
//     appointmentType: "Manager",
//     dateTime: "2025-08-08T08:30:00.000Z",
//     personName: "Devan Bauer",
//     purpose: "Budget discussion",
//     status: "Completed",
//     location: "Conference Room",
//   },
//   {
//     id: 8,
//     appointmentType: "Visitor",
//     dateTime: "2025-08-08T15:00:00.000Z",
//     personName: "Leia Armstrong",
//     purpose: "Partnership proposal",
//     status: "Pending",
//     location: "Meeting Room 2",
//   },
//   {
//     id: 9,
//     appointmentType: "Reception",
//     dateTime: "2025-08-09T12:45:00.000Z",
//     personName: "Sky Palmer",
//     purpose: "Document submission",
//     status: "Confirmed",
//     location: "Meeting Room 2",
//   },
//   {
//     id: 10,
//     appointmentType: "Manager",
//     dateTime: "2025-08-09T17:30:00.000Z",
//     personName: "Joslyn Morrison",
//     purpose: "Budget discussion",
//     status: "Pending",
//     location: "Meeting Room 2",
//   },
//   {
//     id: 11,
//     appointmentType: "Reception",
//     dateTime: "2025-08-10T10:00:00.000Z",
//     personName: "Camille Stewart",
//     purpose: "Document submission",
//     status: "Completed",
//     location: "Meeting Room 2",
//   },
// ];
