// export const myIncidentReportsData = [
//   {
//     id: "IR001",
//     incidentId: "IR001",
//     title: "Fall in hallway",
//     description:
//       "Resident slipped in corridor near Acme Corp. The incident occurred on a rainy day.",
//     severity: "High",
//     dateTime: "2025-08-05T10:15:00.000Z",
//     status: "Resolved",
//     consideredDate: "2025-08-04",
//   },
//   {
//     id: "MT001",
//     incidentId: "MT001",
//     title: "Loud noise complaint",
//     description: "Noise disturbance after midnight",
//     severity: "Low",
//     dateTime: "2025-08-05T10:15:00.000Z",
//     status: "Under Review",
//     consideredDate: "-",
//   },
//   {
//     id: "MT002",
//     incidentId: "MT002",
//     title: "Missing wallet",
//     description: "Resident lost wallet in dining area",
//     severity: "Medium",
//     dateTime: "2025-08-05T10:15:00.000Z",
//     status: "Escalated",
//     consideredDate: "-",
//   },
//   {
//     id: "MT003",
//     incidentId: "MT003",
//     title: "Failing AC Unit",
//     description: "Resident slipped in corridor near A...",
//     severity: "High",
//     dateTime: "2025-08-05T10:15:00.000Z",
//     status: "Escalated",
//     consideredDate: "-",
//   },
//   {
//     id: "MT004",
//     incidentId: "MT004",
//     title: "Stove Not Igniting",
//     description: "Resident slipped in corridor near A...",
//     severity: "Low",
//     dateTime: "2025-08-05T10:15:00.000Z",
//     status: "Resolved",
//     consideredDate: "-",
//   },
//   {
//     id: "MT005",
//     incidentId: "MT005",
//     title: "Dryer Vent Issue",
//     description: "Resident slipped in corridor near A...",
//     severity: "Medium",
//     dateTime: "2025-08-05T10:15:00.000Z",
//     status: "Pending",
//     consideredDate: "-",
//   },
//   {
//     id: "MT006",
//     incidentId: "MT006",
//     title: "Showerhead Leak",
//     description: "Resident slipped in corridor near A...",
//     severity: "High",
//     dateTime: "2025-08-05T10:15:00.000Z",
//     status: "Resolved",
//     consideredDate: "-",
//   },
//   {
//     id: "MT007",
//     incidentId: "MT007",
//     title: "HVAC System Failure",
//     description: "Resident slipped in corridor near A...",
//     severity: "Low",
//     dateTime: "2025-08-05T10:15:00.000Z",
//     status: "Escalated",
//     consideredDate: "-",
//   },
//   {
//     id: "MT008",
//     incidentId: "MT008",
//     title: "Sliding Door Stuck",
//     description: "Resident slipped in corridor near A...",
//     severity: "Medium",
//     dateTime: "2025-08-05T10:15:00.000Z",
//     status: "Escalated",
//     consideredDate: "-",
//   },
//   {
//     id: "MT009",
//     incidentId: "MT009",
//     title: "Cracked Sidewalk",
//     description: "Resident slipped in corridor near A...",
//     severity: "High",
//     dateTime: "2025-08-05T10:15:00.000Z",
//     status: "Under Review",
//     consideredDate: "-",
//   },
//   {
//     id: "MT010",
//     incidentId: "MT010",
//     title: "Broken Sprinkler",
//     description: "Resident slipped in corridor near A...",
//     severity: "Low",
//     dateTime: "2025-08-05T10:15:00.000Z",
//     status: "Resolved",
//     consideredDate: "-",
//   },
//   {
//     id: "MT011",
//     incidentId: "MT011",
//     title: "Gutter Overflow",
//     description: "Resident slipped in corridor near A...",
//     severity: "Medium",
//     dateTime: "2025-08-05T10:15:00.000Z",
//     status: "Escalated",
//     consideredDate: "-",
//   },
//   {
//     id: "MT012",
//     incidentId: "MT012",
//     title: "Blocked Fire Exit",
//     description: "Resident slipped in corridor near A...",
//     severity: "High",
//     dateTime: "2025-08-05T10:15:00.000Z",
//     status: "Resolved",
//     consideredDate: "-",
//   },
// ];
