export const signInOutRequestsData = [
  {
    id: 1,
    date: "2024-01-15",
    type: "Sign In",
    visitor: "John Smith",
    purpose: "Business Meeting",
    timeIn: "09:00 AM",
    timeOut: "11:30 AM",
    status: "Approved",
    requestedBy: "Admin",
    approvedBy: "Manager",
  },
  {
    id: 2,
    date: "2024-01-16",
    type: "Sign Out",
    visitor: "Maria Garcia",
    purpose: "Delivery",
    timeIn: "02:00 PM",
    timeOut: "02:45 PM",
    status: "Pending",
    requestedBy: "Security",
    approvedBy: "-",
  },
  {
    id: 3,
    date: "2024-01-17",
    type: "Sign In",
    visitor: "Robert Johnson",
    purpose: "Maintenance",
    timeIn: "08:30 AM",
    timeOut: "05:00 PM",
    status: "Approved",
    requestedBy: "Admin",
    approvedBy: "Manager",
  },
  {
    id: 4,
    date: "2024-01-18",
    type: "Sign Out",
    visitor: "Lisa Anderson",
    purpose: "Guest Visit",
    timeIn: "06:00 PM",
    timeOut: "09:00 PM",
    status: "Rejected",
    requestedBy: "Resident",
    approvedBy: "Security",
  },
  {
    id: 5,
    date: "2024-01-19",
    type: "Sign In",
    visitor: "David Wilson",
    purpose: "Inspection",
    timeIn: "10:00 AM",
    timeOut: "12:00 PM",
    status: "Pending",
    requestedBy: "Admin",
    approvedBy: "-",
  },
];
